### ISSUE TITLE
Emoji One

### ISSUE THREAD

**Issue by JosefJezek** [notwaldorf/emoji-selector#4]
Could you replace emojilib with better Emoji One?

https://github.com/Ranks/emojione

**Comment by notwaldorf** [comment]
What are the advantages to Emoji One? I like emojilib because it uses the native OS emoji fonts, and doesn't have to actually store any glyphs. And the keywords are pretty useful.

**Comment by JosefJezek** [comment]
Emoji on Ubuntu :-(

![image](https://cloud.githubusercontent.com/assets/2110319/12278305/9f719ac4-b980-11e5-9ad1-bfcd84987153.png)

Emoji One is beautiful emoji pack for web apps.

**Comment by JosefJezek** [comment]
I resolved my issue with emoji on Ubuntu

http://www.omgubuntu.co.uk/2014/11/see-install-use-emoji-symbols-ubuntu-linux

![image](https://cloud.githubusercontent.com/assets/2110319/12388045/c7ad7892-bdd0-11e5-9284-809b2825ae76.png)

I see only Unicode emojis. Linux have not color emojis, check out the link

https://askubuntu.com/questions/639552/how-to-get-apple-color-emojis-to-work-on-ubuntu

http://caniemoji.com

**Comment by notwaldorf** [comment]
Closing, as this is an OS specific problem, not one with the element
